
# Derived in part from https://github.com/google/brotli-wheels
#
# Copyright (c) 2009, 2010, 2013-2016 by the Brotli Authors.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


name: Run tests and build wheel and sdist on all supported OS and Python

on: [push, pull_request, workflow_dispatch]

permissions: {}
jobs:
    build_wheels:
        name: Build unicode wheels ${{ matrix.type }} ${{ matrix.arch }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        defaults:
          run:
            shell: bash
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, windows-latest]
                arch: [auto64]
                build: ["cp{310,311,312,313,314}-*"]

                include:
                    - os: ubuntu-latest
                      arch: auto64
                      type: manylinux2014
                      build: "cp{310,311,312,313,314}-*"
                      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014

                    - os: ubuntu-24.04-arm
                      arch: aarch64
                      build: "cp{310,311,312,313,314}-*"
                      CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014

                    - os: macos-latest
                      arch: universal2
                      build: "cp{310,311,312,313,314}-*"

                    - os: windows-latest
                      arch: auto64
                      build: "cp{310,311,312,313,314}-*"

        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
              with:
                persist-credentials: false

            - name: Build wheels and run tests
              uses: pypa/cibuildwheel@8d2b08b68458a16aeb24b64e68a09ab1c8e82084
              env:
                  CIBW_BUILD: ${{ matrix.build }}
                  CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.CIBW_MANYLINUX_X86_64_IMAGE }}
                  CIBW_MANYLINUX_AARCH64_IMAGE: ${{ matrix.CIBW_MANYLINUX_AARCH64_IMAGE }}
                  CIBW_ARCHS: ${{ matrix.arch }}
                  CIBW_TEST_REQUIRES: pytest
                  CIBW_TEST_COMMAND: pytest -vvs {project}/tests

            - name: Collect built wheels
              uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
              with:
                  name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
                  path: ./wheelhouse/*.whl

    test_on_many_oses:
        name: build ${{ matrix.build_type }} - Run tests ${{ matrix.python }} on ${{ matrix.os }} 
        runs-on: ${{ matrix.os }}
        defaults:
          run:
            shell: bash

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm, macos-14, macos-15, macos-15-intel, windows-2022, windows-2025]
                python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
                build_type: ["AHOCORASICK_UNICODE", "AHOCORASICK_BYTES"]

        steps:
            - name: Set up Python
              uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
              with:
                python-version: "${{ matrix.python }}"

            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
              with:
                persist-credentials: false

            - name: Build, install and test
              run: >
                  export ${{ matrix.build_type }}=yes &&
                  set ${{ matrix.build_type }}=yes &&
                  pip install .[testing] &&
                  pytest -vvs

